// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyectoEF;

#nullable disable

namespace proyectoEF.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20230604195652_NewDataForTables")]
    partial class NewDataForTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("proyectoEF.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("6ae7acaa-9324-486f-976c-70b93b5a5eed"),
                            Nombre = "Actividades pendientes",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("6ae7acaa-9324-486f-976c-70b93b5a5e02"),
                            Nombre = "Actividades personales",
                            Peso = 50
                        },
                        new
                        {
                            CategoriaId = new Guid("6ae7acaa-9324-486f-976c-5ac93b5a5e02"),
                            Nombre = "Cosas trabajo",
                            Peso = 100
                        });
                });

            modelBuilder.Entity("proyectoEF.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("8de7acaa-9324-486f-976c-70b93b5a5eed"),
                            CategoriaId = new Guid("6ae7acaa-9324-486f-976c-70b93b5a5eed"),
                            FechaCreacion = new DateTime(2023, 6, 4, 14, 56, 52, 721, DateTimeKind.Local).AddTicks(4398),
                            PrioridadTarea = 1,
                            Puntos = 0,
                            Titulo = "Pago de servicios públicos"
                        },
                        new
                        {
                            TareaId = new Guid("9ce7acaa-9324-486f-976c-70b93b5a5eed"),
                            CategoriaId = new Guid("6ae7acaa-9324-486f-976c-70b93b5a5e02"),
                            FechaCreacion = new DateTime(2023, 6, 4, 14, 56, 52, 721, DateTimeKind.Local).AddTicks(4448),
                            PrioridadTarea = 0,
                            Puntos = 0,
                            Titulo = "Terminar serie en Netflix"
                        },
                        new
                        {
                            TareaId = new Guid("9ce7acaa-1234-486f-976c-70b93b5a5eed"),
                            CategoriaId = new Guid("6ae7acaa-9324-486f-976c-5ac93b5a5e02"),
                            FechaCreacion = new DateTime(2023, 6, 4, 14, 56, 52, 721, DateTimeKind.Local).AddTicks(4452),
                            PrioridadTarea = 2,
                            Puntos = 0,
                            Titulo = "Reparar bug de React.js"
                        });
                });

            modelBuilder.Entity("proyectoEF.Models.Tarea", b =>
                {
                    b.HasOne("proyectoEF.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("proyectoEF.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
